name: using_climate_data
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - jupyter
  - ipywidgets
  - ipykernel
  - pandas
  - xarray
  - iris
  - cartopy
  - bokeh
  - scikit-learn
  - jupyterlab
  - boto3
  - s3fs
  - intake
  - intake-esm
  - nc-time-axis
  - seaborn