name: using-climate-data
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - jupyter
  - ipywidgets
  - ipykernel
  - pandas
  - xarray
  - iris
  - cartopy
  - bokeh
  - scikit-learn
  - jupyterlab